export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    ADD_SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    CLEAR_LIST: "CLEAR_LIST",
    RATE_BEER: "RATE_BEER"
    
}